model:
  name: "bert-base-uncased"
  max_num_labels: 6

training:
  num_steps: 1000 
  batch_size: 32
  learning_rate: 2e-5
  optimizer: "adamw"
  epochs : 60

data:
  synthetic_data_path: "/content/drive/MyDrive/Projet Urchadee/Poly encoder : multilabel classification/data/data.json"